import csv
import random

def load_random_story(filename):
    with open(filename, 'r') as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        random_row = random.choice(rows)
        return random_row

def display_and_play_game(story_data):
    summary = story_data['summary'].replace('\n', ' ').strip()
    print("Summary:", ". ".join(summary.split(". ")[:2]))
    print()
    
    # Remove newline characters from story and generated_story
    human_story = story_data['story'].replace('\n', ' ').strip()
    gpt_story = story_data['generated_story'].replace('\n', ' ').strip()
    
    # Randomize the order to display the stories
    stories = [("Human", human_story), ("GPT", gpt_story)]
    random.shuffle(stories)

    for i, (label, story) in enumerate(stories, 1):
        print(f"Story {i}:")
        print(story)
        print()

    guess = input("Which story do you think is human generated? Enter 1 or 2: ")

    if stories[int(guess) - 1][0] == "Human":
        print("Correct! That story was human generated.")
    else:
        print("Wrong! That story was generated by GPT.")

if __name__ == '__main__':
    csv_file = 'datasets/hcV3-imagined-stories-with-generated.csv'
    story_data = load_random_story(csv_file)
    display_and_play_game(story_data)
